-- Insert Categories
INSERT INTO categories (name) VALUES 
('LivingSpaces'), 
('WorkSpaces'), 
('RetailSpaces'), 
('StorageSpaces'), 
('EventSpaces'), 
('RecreationalSpaces'), 
('TemporaryLodging'), 
('MiscellaneousSpaces');

-- Insert Subcategories with Descriptions
INSERT INTO subcategories (category_id, name, description) VALUES
(1, 'Private Rooms', 'Individual rooms within shared apartments or houses.'), 
(1, 'Shared Apartments', 'Entire apartments shared by multiple tenants.'), 
(1, 'Dormitories/Hostels', 'Shared living spaces for students or workers.'), 
(1, 'Studio Apartments', 'Smaller, self-contained units.'), 
(1, 'Family Homes', 'Houses available for co-living or partial rental.'), 
(1, 'Co-living Spaces', 'Fully furnished spaces designed for shared living.'),
(2, 'Private Offices', 'Small offices for individual use.'), 
(2, 'Shared Offices', 'Spaces where multiple individuals or teams can work.'), 
(2, 'Co-working Spaces', 'Flexible, open-plan workspaces.'), 
(2, 'Studios/Workshops', 'Creative spaces for art, design, or manufacturing.'), 
(2, 'Conference/Meeting Rooms', 'Bookable spaces for business meetings.'), 
(2, 'Hot Desks', 'Short-term, non-dedicated desks in co-working spaces.'),
(3, 'Market Stalls', 'Small spaces in markets or bazaars.'),
(3, 'Shared Shops/Stalls', 'Spaces where multiple vendors can co-share a retail unit.'), 
(3, 'Shopfronts', 'Retail units in malls or high-street areas.'), 
(3, 'Pop-Up Spaces', 'Short-term spaces for events or seasonal businesses.'), 
(3, 'Kiosks', 'Compact retail setups in malls or transport hubs.'), 
(3, 'Food Carts/Stalls', 'Spaces for mobile or semi-permanent food businesses.'),
(4, 'Personal Storage Units', 'Small spaces for individual storage needs.'), 
(4, 'Garage/Car Storage', 'Spaces for vehicles or larger items.'), 
(4, 'Warehouse Space', 'Industrial-scale storage solutions.'), 
(4, 'Basement/Attic Spaces', 'Extra storage within residential or commercial properties.'),
(5, 'Banquet Halls', 'Large spaces for weddings, parties, or gatherings.'), 
(5, 'Outdoor Venues', 'Gardens, terraces, or open fields.'), 
(5, 'Community Halls', 'Spaces for local events or group activities.'), 
(5, 'Studios', 'For photography, videography, or small productions.'),
(6, 'Gym/Workout Spaces', 'Areas for personal or shared fitness activities.'), 
(6, 'Playgrounds', 'Spaces suitable for childcare or recreational activities.'), 
(6, 'Hobby Rooms', 'Dedicated spaces for crafts, music, or other hobbies.'), 
(6, 'Sports Courts', 'For tennis, basketball, etc.'),
(7, 'Short-Term Rentals', 'Daily or weekly lodging options.'), 
(7, 'Vacation Homes', 'For short-term leisure stays.'), 
(7, 'Hostels', 'Affordable, temporary housing options.'),
(8, 'Parking Spaces', 'For cars, bikes, or other vehicles.'), 
(8, 'Kitchen Spaces', 'Shared or rentable kitchens for catering or food prep.'), 
(8, 'Garden/Allotments', 'Land for gardening or small-scale farming.'), 
(8, 'Rooftop Spaces', 'For small events or relaxation.'), 
(8, 'Shared Vehicles (Addon)', 'For projects with shared transport.');


INSERT INTO amenities (name, description) VALUES
('Wi-Fi', 'High-speed internet access.'),
('Parking', 'Available parking space for vehicles.'),
('Air Conditioning', 'Cooling system for comfort.'),
('Heating', 'Heating system for warmth.'),
('Kitchen', 'Access to cooking facilities.'),
('Laundry', 'On-site laundry facilities.'),
('Gym', 'Fitness center available.'),
('Pool', 'Swimming pool access.'),
('Pet Friendly', 'Allows pets.'),
('Furnished', 'Fully furnished living space.');